version: '3'
services:
  app:
    tty: true
    build: .
    ports:
      - "${ENGINE_APP_PORT-8400}:2112"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    depends_on:
      - redis
      - mongo
    restart: on-failure
    entrypoint: node_modules/.bin/gulp
    environment:
      NODE_ENV: development
      MONGO_DSN: mongodb://mongo:27017/hydra
      REDIS_DSN: redis://redis:6379/0
      PORT: 2112
      MONGOOSE_DEBUG: ${MONGOOSE_DEBUG}
      DEBUG: ${DEBUG}
  redis:
    image: redis:alpine
  mongo:
    image: mongo:3.6
    volumes:
      - mongodb:/data/db
    ports:
      - "${ENGINE_DB_PORT-8401}:27017"
volumes:
  node_modules: {}
  mongodb: {}
